Feat/download all files
FlowSquad/bpm-repo-client pull request #26
Opened 2022-10-18 11:57 UTC by J-Mertl

2022-10-19 11:08 UTC, J-Mertl commented
fixes made:
- deployment Entries can't move over the timestamp anymore, and instead move into a second line (similar to the bugfix regarding normal Entries)
- added Tooltips to all Headerbuttons by adding it to the class Actionbutton
- fixed the deployment download; up to now downloaded a .html, now the actual file (e.g.: .bpmn)

feature added:
- added a project/repository zip-download button and its functionality in RepositoryFIleSection & RepositorySharedSection; as well as the backend connection in FileUtils

2022-10-19 11:22 UTC, lmoesle requested changes
👍🏻 Gut gemacht. Du musst dir aber nochmal das Thema mit den Translation anschauen, die stimmen glaube ich nicht und ein bisschen was könnte man noch refactoren.

2022-10-19 11:22 UTC, lmoesle commented on src/components/Header/DownloadButton.tsx
> +            label={t("Download Project")}
Du musst noch die Translation anlegen unter public/translations

2022-10-21 08:20 UTC, lmoesle approved these changes

2022-10-21 08:21 UTC, merged